import {
    Embeddable,
    Embedded,
    Entity,
    Index,
    ManyToOne,
    PrimaryKey,
    Property,
    Ref,
    SerializedPrimaryKey,
} from '@mikro-orm/core';
import { ObjectId } from '@mikro-orm/mongodb';

import { GuildData } from './guild.js';
import { EventType } from '../../enums/index.js';
import { TimeUtils } from '../../utils/index.js';

// Used to ensure we have language keys for all multipliers
// Now supports decimal values for anniversary events (1.25, 1.5, etc.)
export type XpMultiplier = number;

// The idea of this is we could add things like, message xp min/max, voice xp amount, etc.
@Embeddable()
export class XpProperties {
    @Property()
    multiplier!: XpMultiplier;
}

@Embeddable()
export class TimeProperties {
    @Property()
    startTime!: string;

    @Property()
    endTime!: string;

    // Used so we don't send duplicate messages when the event starts
    @Property()
    hasStarted = false;

    // Used so we don't send duplicate messages when the event ends
    @Property()
    hasEnded = false;

    // Used so we don't send duplicate announcement messages when the event is announced that it will be in 2 weeks
    @Property()
    hasAnnounced = false;

    // Used for fast checks if the event is active
    @Property()
    isActive = false;
}

@Entity({ collection: 'events' })
@Index({ properties: ['guild'] })
export class EventData {
    @PrimaryKey()
    _id!: ObjectId;

    @SerializedPrimaryKey()
    id!: string;

    @Property()
    created = TimeUtils.now().toISO();

    // Used to determine if the event was auto-generated by the bot (Double XP Weekends, etc.)
    @Property()
    autoGenerated = false;

    @Property()
    eventType!: EventType;

    @Embedded({ object: true })
    timeProperties = new TimeProperties();

    @Embedded({ object: true })
    xpProperties = new XpProperties();

    @ManyToOne()
    guild!: Ref<GuildData>;

    constructor(guild: Ref<GuildData>, eventType: EventType, startTime: string, endTime: string) {
        this.guild = guild;
        this.eventType = eventType;
        this.timeProperties.startTime = startTime;
        this.timeProperties.endTime = endTime;
    }
}
